### ISSUE TITLE
When using alternative display format, day/month are reset on year change

### ISSUE THREAD

**Issue by neokoenig** [tanvir0604/vue-dropdown-datepicker#1]
You can see the behaviour here:
https://tanvir0604.github.io/vue-dropdown-datepicker/

In the Alternative Display Format example.

You would naturally want to fill this in from L->R, so Month  / Day / Year, but if you select the Month, then Day, and then finally the Year, the change of year value resets the Month & Day, meaning you have to go back and re-enter the values.

**Comment by tanvir0604** [comment]
Hi,
Thanks for notifying the issue.
The problem is,date validation maintains the hierarchy of Y-m-d.So if you select year and month,then the days will be loaded accordingly.Suppose you have selected 2004 and feb then you will get options to select 29th.So after selecting year,the day value will be reset.
I am going to work on this issue and trying to find out a suitable solution.Thanks again

**Comment by neokoenig** [comment]
Any luck on this?

**Comment by tanvir0604** [comment]
Please check if the problem is solved.Here I got a pull request

https://github.com/tanvir0604/vue-dropdown-datepicker/pull/3

**Comment by neokoenig** [comment]
Can confirm that pull request fixes this for me! thanks.

**Comment by neokoenig** [comment]
PS, if we could get a new release on npm with these fixes in that would be great

**Comment by tanvir0604** [comment]
Thanks for notifying,it is published already.
